[versions]
# Plugins
shadow = "9.3.1"
lombok = "8.10.2"

# Libraries
paper-api = "1.20.4-R0.1-SNAPSHOT"
folia-api = "1.20.2-R0.1-SNAPSHOT"
spigui = "v1.4.1"

worldguard = "7.1.0-SNAPSHOT"
griefprevention = "16.18.4"
lands = "7.13.1"

vault = "1.7.1"
placeholder-api = "2.11.6"
boosted-yaml = "1.3.7"
bstats = "3.1.0"

guice = '7.0.0'
okhttp = '4.12.0'

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
folia-api = { module = "dev.folia:folia-api", version.ref = "folia-api" }

worldguard = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldguard" }
griefprevention = { module = "com.github.GriefPrevention:GriefPrevention", version.ref = "griefprevention" }
lands = { module = "com.github.angeschossen:LandsAPI", version.ref = "lands" }
spigui = { module = "com.samjakob:SpiGUI", version.ref = "spigui" }

vault = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vault" }
placeholder-api = { module = "me.clip:placeholderapi", version.ref = "placeholder-api" }
boosted-yaml = { module = "dev.dejvokep:boosted-yaml", version.ref = "boosted-yaml" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

guice = { module = "com.google.inject:guice", version.ref = "guice" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
